/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhopoon3;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;




/**
 *
 * @author PICHAU
 */
public class Cadastro extends javax.swing.JFrame {

    
    int xMouse;
    int yMouse;
    

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        centralizarComponente();
    }
    
    public void centralizarComponente() { Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension dw = getSize();
    setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastroSair = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        txtCadastroNomeCompleto = new javax.swing.JTextField();
        txtCadastroCPF = new javax.swing.JTextField();
        txtCadastroSenha = new javax.swing.JTextField();
        txtCadastroCSenha = new javax.swing.JTextField();
        btCriarConta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setMinimumSize(new java.awt.Dimension(720, 720));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 720));
        setSize(new java.awt.Dimension(720, 720));
        getContentPane().setLayout(null);

        btCadastroSair.setBorderPainted(false);
        btCadastroSair.setContentAreaFilled(false);
        btCadastroSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastroSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroSairActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastroSair);
        btCadastroSair.setBounds(670, 0, 50, 30);

        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseDragged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 720, 30);

        txtCadastroNomeCompleto.setBorder(null);
        getContentPane().add(txtCadastroNomeCompleto);
        txtCadastroNomeCompleto.setBounds(210, 241, 260, 36);

        txtCadastroCPF.setBorder(null);
        txtCadastroCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastroCPFActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastroCPF);
        txtCadastroCPF.setBounds(210, 309, 260, 37);

        txtCadastroSenha.setBorder(null);
        getContentPane().add(txtCadastroSenha);
        txtCadastroSenha.setBounds(210, 376, 260, 36);

        txtCadastroCSenha.setBorder(null);
        getContentPane().add(txtCadastroCSenha);
        txtCadastroCSenha.setBounds(210, 444, 260, 34);

        btCriarConta.setBorderPainted(false);
        btCriarConta.setContentAreaFilled(false);
        btCriarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarContaActionPerformed(evt);
            }
        });
        getContentPane().add(btCriarConta);
        btCriarConta.setBounds(100, 560, 520, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhopoon3/Resources/cadastro720.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void btCadastroSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroSairActionPerformed
        // TODO add your handling code here:
        
        Main form1 = new Main(); 
        form1.setVisible(true); 
        dispose();
    }//GEN-LAST:event_btCadastroSairActionPerformed

    private void btCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarContaActionPerformed
        // TODO add your handling code here:
        
        String n = txtCadastroNomeCompleto.getText();
        String c = txtCadastroCPF.getText();
        int s = Integer.parseInt(txtCadastroSenha.getText());
        int cs = Integer.parseInt(txtCadastroCSenha.getText());
        
       
        
            
        
        if(s == cs && (s<=9999 && s>=1000))
        {
                       
            
             
             String sql = "SELECT * FROM `vw.contas_bancarias` ORDER BY numeroconta DESC LIMIT 1";
            PreparedStatement ps = null;
             
             
             try {
       
             ps = Conexao.getConexao().prepareStatement(sql);
             ResultSet rs = ps.executeQuery();
             Agencia.criarConta(s, 0);
             Agencia.criarCliente(n, c);
             if(rs.next())
             {
             JOptionPane.showMessageDialog(rootPane, "Conta Criada com Sucesso! Login:" + (rs.getInt("numeroconta")+1), "Cadastro", 1);
             }
             
        } catch (SQLException ex) {
            System.out.println("Erro" + ex);
            
        }
           
                  
                       
            
        }
        else if(s != cs){
            JOptionPane.showMessageDialog(rootPane, "Senhas Diferentes", "Erro", 1);
        }
        else if(s>9999 || s<1000){
            JOptionPane.showMessageDialog(rootPane, "Digite uma senha de 4 digitos!", "Erro", 1);
        }
        
        
    }//GEN-LAST:event_btCriarContaActionPerformed

    private void txtCadastroCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastroCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastroCPFActionPerformed

    private void jTabbedPane1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseDragged
        // TODO add your handling code here:
        
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        setLocation(X - xMouse, Y - yMouse);
    }//GEN-LAST:event_jTabbedPane1MouseDragged

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jTabbedPane1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastroSair;
    private javax.swing.JButton btCriarConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCadastroCPF;
    private javax.swing.JTextField txtCadastroCSenha;
    private javax.swing.JTextField txtCadastroNomeCompleto;
    private javax.swing.JTextField txtCadastroSenha;
    // End of variables declaration//GEN-END:variables
}
