/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhopoon3;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author PICHAU
 */
public class Main extends javax.swing.JFrame{

    /**
     * Creates new form Main
     */
    int xMouse, yMouse;
    
    public Main() {
        initComponents();
        centralizarComponente();
    }
    
    public void centralizarComponente() { Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension dw = getSize();
    setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        txtSenhaMain = new javax.swing.JPasswordField();
        txtLoginMain = new javax.swing.JTextField();
        btLogarMain = new javax.swing.JButton();
        btCadastroMain = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 720));
        getContentPane().setLayout(null);

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 0, 50, 30);

        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseDragged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 720, 40);

        txtSenhaMain.setBorder(null);
        txtSenhaMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaMainActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenhaMain);
        txtSenhaMain.setBounds(220, 357, 260, 36);

        txtLoginMain.setBorder(null);
        txtLoginMain.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLoginMain.setMinimumSize(new java.awt.Dimension(64, 19));
        txtLoginMain.setPreferredSize(new java.awt.Dimension(63, 19));
        txtLoginMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginMainActionPerformed(evt);
            }
        });
        getContentPane().add(txtLoginMain);
        txtLoginMain.setBounds(220, 290, 260, 35);

        btLogarMain.setContentAreaFilled(false);
        btLogarMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogarMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarMainActionPerformed(evt);
            }
        });
        getContentPane().add(btLogarMain);
        btLogarMain.setBounds(90, 540, 540, 90);

        btCadastroMain.setContentAreaFilled(false);
        btCadastroMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastroMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroMainActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastroMain);
        btCadastroMain.setBounds(160, 430, 90, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhopoon3/Resources/main720.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 720, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogarMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarMainActionPerformed
        // TODO add your handling code here:
        

        try {
            int n = Integer.parseInt(txtLoginMain.getText());
            int s = Integer.parseInt(txtSenhaMain.getText());
            ResultSet rs  = Agencia.logar(n, s);
            
            

            if (rs.next()) {
                Menu form3 = new Menu(rs);
                form3.setVisible(true);
                dispose();
            } else {

                JOptionPane.showMessageDialog(rootPane, "Senha ou Login não encontrados");
            }

        } catch (SQLException ex) {
            System.out.println("" + ex);
        }

        
    }//GEN-LAST:event_btLogarMainActionPerformed

    private void btCadastroMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroMainActionPerformed
        Cadastro form2 = new Cadastro();
        form2.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastroMainActionPerformed

    private void txtLoginMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginMainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseDragged
        // TODO add your handling code here:
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        setLocation(X - xMouse, Y - yMouse);
    }//GEN-LAST:event_jTabbedPane1MouseDragged

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
       
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void txtSenhaMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaMainActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastroMain;
    private javax.swing.JButton btLogarMain;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtLoginMain;
    private javax.swing.JPasswordField txtSenhaMain;
    // End of variables declaration//GEN-END:variables
}
