/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhopoon3;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PICHAU
 */
public class Transferencia extends javax.swing.JFrame {

    /**
     * Creates new form Transferencia
     */
    /**
     * Creates new form Menu
     * @param rs
     */
    ResultSet resultglobal;
    
    String nome;
    String cpf;
    int numeroconta;
    int senha;
    double saldo;
    
    int xMouse;
    int yMouse;
    
    public Transferencia(ResultSet rs) {
        initComponents();
        centralizarComponente();
        
        
        ResultSet result = rs;
        resultglobal = result;
        try {
            
            
            nome = result.getString("nome");
            cpf = result.getString("cpf");
            numeroconta = result.getInt("numeroconta");
            saldo = result.getDouble("saldo");
            senha = result.getInt("senha");
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
     public void centralizarComponente() { Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension dw = getSize();
    setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        txtNC = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btTransferencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transferencia");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 292));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 292));
        getContentPane().setLayout(null);

        jButton1.setActionCommand("btSair");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(495, 3, 50, 40);

        jTabbedPane2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseDragged(evt);
            }
        });
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane2MousePressed(evt);
            }
        });
        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 550, 40);

        txtNC.setBorder(null);
        txtNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNCActionPerformed(evt);
            }
        });
        getContentPane().add(txtNC);
        txtNC.setBounds(240, 71, 260, 43);

        txtValor.setBorder(null);
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor);
        txtValor.setBounds(240, 137, 260, 42);

        btTransferencia.setBorderPainted(false);
        btTransferencia.setContentAreaFilled(false);
        btTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btTransferencia);
        btTransferencia.setBounds(0, 230, 550, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhopoon3/Resources/TRANSFERENCIA.jpg"))); // NOI18N
        jLabel1.setText("Transferencia");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 153), 3, true));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 292);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNCActionPerformed

    private void btTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferenciaActionPerformed
        // TODO add your handling code here:
        
       double valor = Double.parseDouble(txtValor.getText());
        int nc = Integer.parseInt(txtNC.getText());
        ResultSet rs2 = Agencia.getInfo(nc);
        try {
            if(rs2.next())
            {
                if(valor<= saldo)
                {
                boolean checar = Agencia.Depositar(valor, nc, rs2.getDouble("saldo"));
                boolean checar2 = Agencia.Sacar(valor, numeroconta, saldo);
                if(checar == true && checar2 == true && (numeroconta != nc))
                {
                JOptionPane.showMessageDialog(rootPane, "Transferencia Realizada", "Transferencia", 1);
                dispose();
                }
                else
                {
                JOptionPane.showMessageDialog(rootPane, "Erro!\n Não é permitido transferir para a sua própria conta bancária", "Erro", 1);
                }
                }
                else
                {
                JOptionPane.showMessageDialog(rootPane, "Saldo Insuficiente", "Erro", 1);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Conta não encontrada", "Erro", 1);
            }

        } catch (SQLException ex) {
            System.out.println("Erro" + ex);
        }
            
        
        
    }//GEN-LAST:event_btTransferenciaActionPerformed

    private void jTabbedPane2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jTabbedPane2MousePressed

    private void jTabbedPane2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseDragged
        // TODO add your handling code here:
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        setLocation(X - xMouse, Y - yMouse);
    }//GEN-LAST:event_jTabbedPane2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    /**
     * @param args the command line arguments
     * @param rs
     */
    public static void main(String args[], ResultSet rs) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferencia(rs).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTransferencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtNC;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
